window.clubs = [
  { name: "Blox", id: "429" },
  { name: "CC Vest", id: "210" },
  { name: "Colosseum", id: "212" },
  { name: "Kalbakken", id: "213" },
  { name: "Linderud", id: "214" },
  { name: "Karlsrud", id: "216" },
  { name: "Lambertseter", id: "217" }
  /*,
  { name: "Nesttun", id: "104" },
  { name: "Drammen", id: "106" },
  { name: "Bergen LHG", id: "114" },
  { name: "Hoff", id: "116" },
  { name: "Hellerud", id: "130" },
  { name: "Vestkanten", id: "131" },
  { name: "Åsane", id: "132" },
  { name: "Sarpsborg", id: "133" },
  { name: "Tromsø", id: "142" },
  { name: "Lillestrøm", id: "146" },
  { name: "Solli Plass", id: "147" },
  { name: "Schous plass", id: "148" },
  { name: "Metro", id: "149" },
  { name: "Bekkestua", id: "152" },
  { name: "Langnes", id: "154" },
  { name: "Bislett", id: "156" },
  { name: "Storo", id: "157" },
  { name: "Sagene", id: "158" },
  { name: "Kampen", id: "161" },
  { name: "Tasta", id: "162" },
  { name: "Vinderen", id: "163" },
  { name: "Akersgata", id: "166" },
  { name: "Sandviken", id: "167" },
  { name: "Sandnes", id: "171" },
  { name: "Njårdhallen", id: "173" },
  { name: "Nydalen", id: "178" },
  { name: "Wergeland Terrasse", id: "182" },
  { name: "Strømsø", id: "184" },
  { name: "Storhaug", id: "186" },
  { name: "Lagunen", id: "187" },
  { name: "Danmarksplass", id: "188" },
  { name: "Slemmestad", id: "189" },
  { name: "Asker", id: "206" },
  { name: "Billingstad", id: "207" },
  { name: "Bjørvika", id: "208" },
  { name: "Carl Berner", id: "209" },
  { name: "CC Vest", id: "210" },
  { name: "Colosseum", id: "212" },
  { name: "Kalbakken", id: "213" },
  { name: "Linderud", id: "214" },
  { name: "Karlsrud", id: "216" },
  { name: "Lambertseter", id: "217" },
  { name: "Ringnes Park", id: "218" },
  { name: "Ryen", id: "219" },
  { name: "Sjølyst", id: "220" },
  { name: "Ullevaal Stadion", id: "221" },
  { name: "Sandvika Panorama", id: "222" },
  { name: "Jessheim", id: "223" },
  { name: "Kolbotn", id: "224" },
  { name: "Tunejordet", id: "227" },
  { name: "Kokstad", id: "230" },
  { name: "Damsgård", id: "231" },
  { name: "Bryne", id: "232" },
  { name: "Madla", id: "233" },
  { name: "Trim Towers", id: "234" },
  { name: "Hillevåg", id: "236" },
  { name: "Herbarium", id: "237" },
  { name: "Vågsbygd", id: "240" },
  { name: "Røa", id: "251" },
  { name: "Fornebu", id: "253" },
  { name: "Porsgrunn", id: "254" },
  { name: "Porselensfabrikken", id: "255" },
  { name: "Klosterøya", id: "256" },
  { name: "Aquarama", id: "258" },
  { name: "Hasle", id: "262" },
  { name: "Fagerborg", id: "263" },
  { name: "Fredrikstad", id: "266" },
  { name: "Stadionparken", id: "267" },
  { name: "Oasen", id: "268" },
  { name: "Ila", id: "269" },
  { name: "Bekkestua Stasjon", id: "270" },
  { name: "Triaden", id: "271" },
  { name: "Skedsmokorset", id: "272" },
  { name: "SATS Yoga Majorstuen", id: "801" },
  { name: "SATS Yoga Aker Brygge", id: "802" }*/
];
